---
driver:
  name: docker
  use_sudo: false
provisioner:
  name: chef_zero
  require_chef_omnibus: true
platforms:
  - name: ubuntu-14.04
suites:
  - name: default
    run_list:
      - recipe[sudo-user]
