#!/usr/bin/env ruby

# This script creates and deploys a new CloudFront distribution based on the current local configuration.
require_relative '../../deployment'
require 'aws-sdk'
require_relative './cloudfront'

cloudfront = Aws::CloudFront::Client.new
new_config = cloudfront_config(CDO.cloudfront[:pegasus], CDO.http_cache[:pegasus])
response = cloudfront.create_distribution(
  distribution_config: new_config
)
cloudfront.wait_until(:distribution_deployed, id: response.distribution.id) do |waiter|
  waiter.before_wait { |_| puts 'Waiting for distribution to deploy..' }
end
puts 'Distribution creation complete!'
puts "id: #{response.distribution.id}"
