#!/bin/bash
# Run this script to build Docker and AWS images using Packer.
# Works on Linux AMD64 platform.
# Requires `curl` and `unzip` installed on the host machine (for Packer download + install).
set -e

# Download and install Packer to a temp folder.
PACKER_VERSION=0.8.6
PACKER_URL="https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
TMPDIR=~/.cdo
PACKER_PATH=${TMPDIR}/packer
if [ ! -f ${PACKER_PATH}/packer ]; then
  TMPFILE=$(mktemp)
  mkdir -p ${PACKER_PATH}
  curl -L ${PACKER_URL} -o ${TMPFILE}
  unzip -d ${PACKER_PATH} ${TMPFILE}
  rm ${TMPFILE}
fi

export PATH=${PATH}:${PACKER_PATH}
BRANCH=$(git rev-parse --abbrev-ref HEAD)

pushd ../cookbooks
bundle exec berks package /tmp/berks.tar.gz
aws s3 cp --acl="public-read" /tmp/berks.tar.gz s3://cdo-dist/chef/${BRANCH}.tar.gz
popd

ROOT=$(dirname ${PWD})
SSH_PATH=${HOME}/.ssh
PACKER_LOG=1 packer build -var "branch=${BRANCH}" -var "root=${ROOT}" -var "key_path=${SSH_PATH}" packer.json
